### ISSUE TITLE
Support for multiple signatures/fingerprint for the same platform via JSON provided from https://git.io/signatures_json

### ISSUE THREAD

**Issue by naryal2580** [TheBinitGhimire/NtHiM#13]
Please make content key to be iterated via JSON, and check the content through each iterated content making it look something like:

```JSON
{"platforms": [
      {
          "platform": "GitHub Pages",
          "content": [
			"<p><strong>There isn't a GitHub Pages site here.</strong></p>",
                        "For root URLs (like http://example.com/) you must provide an index.html file"
			]
	},
	{...},
]}
```

Cheers!

**Comment by TheBinitGhimire** [comment]
Hello @naryal2580,

Thanks for opening up this issue! I have just added support for multiple signatures for the same platform via the JSON provided at the given URL.

The changes will be live in the upcoming release of **NtHiM**, and for now, you can check out the commit **9cc70f9929636fa84bf33fbc1a713573e8e4a9c6**.

Thanks,
@TheBinitGhimire

**Comment by TheBinitGhimire** [comment]
Hello @naryal2580,

Thanks for opening up this issue! I have just added support for multiple signatures for the same platform via the JSON provided at the given URL.

The changes will be live in the upcoming release of **NtHiM**, and for now, you can check out the commit **9cc70f9929636fa84bf33fbc1a713573e8e4a9c6**.

**_Please note that the existing JSON structuring is also supported!_**

Thanks,
@TheBinitGhimire
