### ISSUE TITLE
[Bug] Crashes when passing huge list using -f 

### ISSUE THREAD

**Issue by sumgr0** [TheBinitGhimire/NtHiM#18]
The tool is crashing and results in the below error:

thread 'main' panicked at 'a parsed Url should always be a valid Uri: InvalidUri(InvalidUriChar)', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.10/src/into_url.rs:44:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2]    19988 abort      NtHiM -f ~/monitor/data/subdom_url
NtHiM -f ~/monitor/data/subdom_url  2.29s user 1.22s system 7% cpu 44.835 total

![image](https://user-images.githubusercontent.com/11391119/150132627-a3c41bff-373e-4abf-b40e-ca16370e4db9.png)

**Comment by TheBinitGhimire** [comment]
Hi there,

Can you please let me know the version of **NtHiM** that you are using? I couldn't reproduce the issue on the latest release version ([**v0.1.3**](https://github.com/TheBinitGhimire/NtHiM/releases/tag/0.1.3)), with a gigabytes large file as well as URLs with characters like %, ^, etc. and unicode characters.

Thanks,
@TheBinitGhimire

**Comment by TheBinitGhimire** [comment]
Hello @sumgr0,

I have successfully reproduced the issue as of now, for two different cases:
* Invalid characters in hostnames (as your error mentions): `InvalidUriChar`
* Very long hostnames (found during my testing): `TooLong`

This seems to be coming through the **http** crate, and [**`src/uri/mod.rs`**](https://github.com/hyperium/http/blob/master/src/uri/mod.rs#L128-L141) file in this crate appears to have several other error types defined:
* InvalidScheme
* InvalidAuthority
* InvalidPort
* InvalidFormat
* SchemeMissing
* AuthorityMissing
* PathAndQueryMissing
* Empty
* SchemeTooLong

I have worked on a fix, and also pushed it to the [**development**](https://github.com/TheBinitGhimire/NtHiM/tree/development) branch for now. The fix will be live in the next release of **NtHiM**.

Thanks for opening up this interesting issue!

Thanks,
@TheBinitGhimire

**Comment by TheBinitGhimire** [comment]
Hello @sumgr0,

The new release of **NtHiM**, i.e. [**v0.1.4**](https://github.com/TheBinitGhimire/NtHiM/releases/tag/0.1.4), is published now, which includes the following fixes:
* Initial URL parsing crashes, and,
* Post URL parsing crashes!

If you are able to reproduce this issue in the new version of **NtHiM**, please re-open this issue and let me know!

Thanks,
@TheBinitGhimire
