### ISSUE TITLE
Compile from source fix.

### ISSUE THREAD

**Issue by gprime31** [TheBinitGhimire/NtHiM#21]
Update rust.
![2022-01-21_08-27](https://user-images.githubusercontent.com/44535257/150534997-b17eb427-9a71-404b-9d2e-2f649cbf36b4.png)

**Comment by gprime31** [comment]
https://www.rust-lang.org/tools/install  and run the sh script.

**Comment by TheBinitGhimire** [comment]
Hello @gprime31,

Thank you for letting me know that updating Rust/Cargo to the latest version enabled you to properly build **NtHiM** from source!

I have made the required changes in the documentation, referencing this issue.

Thanks,
@TheBinitGhimire
