### ISSUE TITLE
[Feature enhancement] Enumerate recursively of domain

### ISSUE THREAD

**Issue by Aju100** [TheBinitGhimire/NtHiM#6]
Hi, @TheBinitGhimire ,

It will be much more awesome if NiHiM can enumerate the domain and its subdomain recursively.

example
`
NtHim -t https://*.example.com
`

**Comment by TheBinitGhimire** [comment]
Hello @Aju100,

As of now, NtHiM is a Sub-domain Takeover Detection tool, and not an enumeration tool. So, it is expected that you have a list of sub-domains already before using NtHiM.

But still, your recommendation is highly helpful, and this shall become a great feature to add in NtHiM, with enumeration and takeover detection combined.

I will look into it soon, and mention this issue whenever there is a sub-domain enumeration feature included in NtHiM.

Thank you for your feature enhancement suggestions!

Thanks,
@TheBinitGhimire

**Comment by TheBinitGhimire** [comment]
Hello **@Aju100**,

As of now, **NtHiM** is a Sub-domain Takeover Detection tool, and not an enumeration tool. So, it is expected that you have a list of sub-domains already before using **NtHiM**.

But still, your recommendation is highly helpful, and this shall become a great feature to add in **NtHiM**, with enumeration and takeover detection combined.

I will look into it soon, and mention this issue whenever there is a sub-domain enumeration feature included in **NtHiM**.

Thank you for your feature enhancement suggestions!

Thanks,
@TheBinitGhimire

**Comment by Aju100** [comment]
Hope you can wishlist in the project timeline.

**Comment by TheBinitGhimire** [comment]
Hello **@Aju100**,

Sure, I will add this feature in the wishlist for the future of **NtHiM**.

Thanks,
**@TheBinitGhimire**
