### ISSUE TITLE
Add Platform/OS support

### ISSUE THREAD

**Issue by naryal2580** [TheBinitGhimire/NtHiM#7]
I would love to see the same tool with Cross-platform releases, with OS/platform including OSX, Linux, BSD.

**Comment by TheBinitGhimire** [comment]
Hello @naryal2580,

Thank you for opening this issue! I will work on publishing releases for other platforms, with reference to this issue, plus let you know when the work is completed.

Thanks,
@TheBinitGhimire

**Comment by TheBinitGhimire** [comment]
Hello @naryal2580,

In the first major release ([**v0.1.0**](https://github.com/TheBinitGhimire/NtHiM/releases/tag/0.1.0)) of **NtHiM**, I have included the pre-compiled binaries for multiple architectures (*aarch64*, *armv7*, *i686* and *x86_64*) and multiple platforms (*Microsoft Windows*, *Linux*, *MacOS*, *Sun Solaris* and *NetBSD*).

With that being done, the things you're looking for in the issue are now available as assets on the latest release of **NtHiM**.

Thank You for opening up this issue, and providing an opportunity for me to include cross-platform binary releases for **NtHiM**!

Thanks,
@TheBinitGhimire
